"""Build the torrc OnionFruitux would hand to its own Tor process."""

from __future__ import annotations

from pathlib import Path

from onionfruitux import bridges
from onionfruitux.config import Config, Route, parse_relay_ports
from onionfruitux.paths import (
    CONTROL_PORT,
    COOKIE_PATH,
    DNS_PORT,
    LOG_PATH,
    SOCKS_PORT,
    TOR_DATA,
    TOR_USER,
    TRANS_PORT,
)

_GEO_CANDIDATES = (
    (Path("/usr/share/tor/geoip"), Path("/usr/share/tor/geoip6")),
    (Path("/var/lib/tor/geoip"), Path("/var/lib/tor/geoip6")),
)


def geoip_paths() -> tuple[Path | None, Path | None]:
    for ipv4, ipv6 in _GEO_CANDIDATES:
        if ipv4.exists():
            return ipv4, ipv6 if ipv6.exists() else None
    return None, None


def render_torrc(cfg: Config, route: Route | None = None) -> str:
    """Return a complete torrc. This function does not start Tor."""
    chosen = route if route is not None else cfg.current_route()
    lines = [
        "# Generated by OnionFruitux. Replaced when the switch turns on.",
        f"User {TOR_USER}",
        f"DataDirectory {TOR_DATA}",
        f"Log notice file {LOG_PATH}",
        "",
        f"SocksPort 127.0.0.1:{SOCKS_PORT}",
        f"TransPort 127.0.0.1:{TRANS_PORT} IsolateClientAddr",
        f"TransPort [::1]:{TRANS_PORT} IsolateClientAddr",
        f"DNSPort 127.0.0.1:{DNS_PORT}",
        f"DNSPort [::1]:{DNS_PORT}",
        "VirtualAddrNetworkIPv4 10.192.0.0/10",
        "VirtualAddrNetworkIPv6 [FC00::]/7",
        "AutomapHostsOnResolve 1",
        "",
        f"ControlPort 127.0.0.1:{CONTROL_PORT}",
        "CookieAuthentication 1",
        f"CookieAuthFile {COOKIE_PATH}",
        "",
    ]
    if chosen.entry or chosen.exit:
        ipv4, ipv6 = geoip_paths()
        lines.append(f"GeoIPFile {ipv4 or '/usr/share/tor/geoip'}")
        lines.append(f"GeoIPv6File {ipv6 or '/usr/share/tor/geoip6'}")
    if chosen.bridge:
        lines.append("# A bridge replaces the entry country.")
        lines.append("UseBridges 1")
        bridge_lines = bridges.lines_for_route(cfg, chosen)
        lines.extend(bridges.plugin_lines(chosen.bridge, bridge_lines))
        for bridge in bridge_lines:
            lines.append(f"Bridge {bridge}")
    elif chosen.entry:
        lines.append(f"EntryNodes {{{chosen.entry}}}")
    if chosen.exit:
        lines.append(f"ExitNodes {{{chosen.exit}}}")
    if chosen.strict:
        lines.append("StrictNodes 1")
    elif chosen.entry or chosen.exit or chosen.bridge:
        lines.append("StrictNodes 0")
    ports = parse_relay_ports(cfg.network.relay_ports)
    if ports:
        reachable = ",".join(f"*:{port}" for port in ports)
        lines.append("FascistFirewall 1")
        lines.append(f"ReachableAddresses {reachable}")
    lines.append("")
    return "\n".join(lines)
