#!/bin/sh
# Build an Arch package without makepkg, so a release can be produced on
# Debian or Ubuntu. packaging/build-arch.sh still runs makepkg on Arch.
set -eu

ROOT=$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)
if ! command -v zstd >/dev/null 2>&1; then
  echo "onionfruitux: zstd is required" >&2
  exit 1
fi

VERSION=$(sed -n 's/^__version__ = "\(.*\)"/\1/p' "$ROOT/onionfruitux/__init__.py")
REL=1
STAGE=$(mktemp -d)
trap 'rm -rf "$STAGE"' EXIT
sh "$ROOT/packaging/stage.sh" "$STAGE/root"

SIZE=$(du -sb "$STAGE/root" | awk '{print $1}')
cat > "$STAGE/root/.PKGINFO" <<EOF
# Generated by OnionFruitux packaging/build-arch-portable.sh
pkgname = onionfruitux
pkgbase = onionfruitux
xdata = pkgtype=pkg
pkgver = ${VERSION}-${REL}
pkgdesc = Send this computer's internet through Tor
url = https://github.com/nitrofireinc-pixel/OnionFruitux
builddate = $(date +%s)
packager = Nitrofire Computing <nitrofireinc@gmail.com>
size = ${SIZE}
arch = any
license = GPL-3.0-or-later
depend = python
depend = tor
depend = nftables
depend = python-pyqt6
depend = polkit
depend = xdg-utils
optdepend = obfs4proxy: obfs4 bridges
optdepend = snowflake-client: Snowflake bridges
EOF
cp "$ROOT/packaging/onionfruitux.install" "$STAGE/root/.INSTALL"

mkdir -p "$ROOT/dist"
OUT="$ROOT/dist/onionfruitux-${VERSION}-${REL}-any.pkg.tar.zst"
tar --format=ustar --owner=0 --group=0 --numeric-owner \
  -C "$STAGE/root" -cf - .PKGINFO .INSTALL usr \
  | zstd -c -19 > "$OUT"
echo "$OUT"
